    name = "gti-api"
    main = "src/index.js"
    compatibility_date = "2026-07-20"
     [[d1_databases]]
      "binding"= "gti_db"
      "database_name"= "gti-db"
      "database_id"= "74054620-296b-4aef-a7a7-c7063b1c257e"
    
  
